# Generated by Django 4.1.2 on 2024-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('transmision', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=20)),
                ('velocidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
