# Generated by Django 4.1.2 on 2024-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
