# Generated by Django 5.0.6 on 2024-06-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Correo', models.CharField(max_length=40)),
                ('Clave', models.CharField(max_length=20)),
            ],
        ),
    ]
