# Generated by Django 5.0.6 on 2024-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Correo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(max_length=20),
        ),
    ]
