# Generated by Django 5.0.6 on 2024-06-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_correo_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Correo',
            field=models.EmailField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
