# Generated by Django 4.1.2 on 2024-06-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Clave',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
