# Generated by Django 4.1.2 on 2024-07-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_clave_cliente_clave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='clave',
            new_name='Clave',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
