# Generated by Django 4.1.2 on 2024-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_clave_cliente_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Correo',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
